services:
  - type: web
    name: ashish-emote-panel
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_panel:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
